<a href="https://colab.research.google.com/github/coll-j/STKI-assignments/blob/main/Pertemuan_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<center><strong>Sistem Temu Kembali Informasi</strong><br />
<strong><font color="blue">Semester Gasal T.A. 2020/2021</font></strong><br />
</center>

<strong>Outline pertemuan minggu ke-3</strong><br />
<li> Membaca dokumen dari file </li>
<li> Representasi vektor </li>
<li> Pembobotan</li>


### Membaca dokumen dari file
<p> Untuk membaca dokumen dari file dapat dilakukan dengan berbagai macam cara, bergantung pada format dari dokumen tersebut </p>

<p><img alt="" src="figures/2_importing_Files.jpg" style="height:400px; width:510px" /><br />
[<a href="http://www.clearcounsel.com/what-happens-to-your-digital-property-after-you-die/" target="_blank"><strong>Image Source</strong></a>]</p>

<p> Berikut ini merupakan list library untuk memparsing dokumen dalam berbagai format </p>
<p>* <a href="https://textract.readthedocs.io/en/stable/&amp;nbsp" target="_blank">https://textract.readthedocs.io/</a> <img alt="" src="figures/2_textract.png" style="height: 239px; width: 600px;" /></p>


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [1]:
!wget https://raw.githubusercontent.com/coll-j/STKI-assignments/main/data/the_matrix_synopsis.txt

--2021-09-19 12:46:00--  https://raw.githubusercontent.com/coll-j/STKI-assignments/main/data/the_matrix_synopsis.txt
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 35738 (35K) [text/plain]
Saving to: ‘the_matrix_synopsis.txt’

the_matrix_synopsis 100%[===================>]  34.90K  --.-KB/s    in 0.003s  

2021-09-19 12:46:01 (11.1 MB/s) - ‘the_matrix_synopsis.txt’ saved [35738/35738]



In [4]:
# Membaca dokumen dengan format .txt
import os

src_name = "the_matrix_synopsis.txt"

docs = list()
with open(src_name, 'r', encoding="utf-8") as fin:
    # membaca seluruh isi dari dokumen
    data = fin.readlines()
    
    # menghilangkan newline ("\n") dan baris yang kosong
    for d in data:
        d_strip = d.strip()
        
        if d_strip:
            docs.append(d_strip)

In [5]:
# Mengecek banyaknya dokumen (note: 1 dokumen = 1 baris)
print("Panjang dokumen: ", len(docs))

# Mengakses isi dari dokumen dengan indeks 1
print(docs[1])

Panjang dokumen:  97
A phone rings and text appears on the screen: "Call trans opt: received. 2-19-98 13:24:18 REC: Log>" As a conversation takes place between Trinity (Carrie-Anne Moss) and Cypher (Joe Pantoliano), two free humans, a table of random green numbers are being scanned and individual numbers selected, creating a series of digits not unlike an ordinary phone number, as if a code is being deciphered or a call is being traced.


In [6]:
# Membaca dokumen dengan format .csv
import os
import pandas as pd

dff = pd.read_csv('https://raw.githubusercontent.com/coll-j/STKI-assignments/main/data/data_tweet.csv')

print(dff)

           Date       Screen Name  ... Timezone Profile Image
0     6/27/2018     @BachtiarLiem  ...      NaN          View
1     6/27/2018  @wikipediaberita  ...      NaN          View
2     6/27/2018     @kompaskampus  ...      NaN          View
3     6/27/2018     @GidiyonDavid  ...      NaN          View
4     6/27/2018  @2019Ada_PilPres  ...      NaN          View
...         ...               ...  ...      ...           ...
2419  6/27/2018      @ahmadvision  ...      NaN          View
2420  6/27/2018  @HorasSumutNews8  ...      NaN          View
2421  6/27/2018      @serambinews  ...      NaN          View
2422  6/27/2018      @inibukanedo  ...      NaN          View
2423  6/27/2018      @tareqAzizii  ...      NaN          View

[2424 rows x 21 columns]


<h3 id="Json-Files">Json Files</h3>

<ul>
	<li>Populer digunakan untuk data dari Media Sosial dan NoSQL</li>
	<li>Portable: File Json memuat nama variabel dan nilainya (tidak seperti XML)</li>
	<li>Plain Text</li>
	<li>Schemaless: Setiap record tidak harus memiliki jumlah field yang tetap seperti csv</li>
	<li>JSON isomorfis dengan &quot;Dictionary&quot; di Python</li>
	<li>Contoh struktur file json:</li>
</ul>

<p><img alt="" src="figures/json.png" style="width: 200px; height: 211px;" /></p>


In [15]:
!wget https://raw.githubusercontent.com/coll-j/STKI-assignments/main/data/contoh.json

--2021-09-19 12:57:02--  https://raw.githubusercontent.com/coll-j/STKI-assignments/main/data/contoh.json
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 58 [text/plain]
Saving to: ‘contoh.json’

contoh.json         100%[===================>]      58  --.-KB/s    in 0s      

2021-09-19 12:57:02 (2.65 MB/s) - ‘contoh.json’ saved [58/58]



In [16]:
# Membaca dokumen dengan format .json
import json

src_name = "contoh.json"

with open(src_name) as fin:
    data = json.load(fin)
    
data

{'mobil': 'BMW', 'motor': 'Forza', 'nama': 'Mukidi', 'umur': 19}

In [17]:
# Membaca teks dari halaman website
import urllib.request
from bs4 import BeautifulSoup as bs

URL = "https://www.its.ac.id/informatika/fasilitas/laboratorium/laboratorium-komputasi-cerdas-dan-visi/"
doc = urllib.request.urlopen(URL).read()
doc = bs(doc, 'lxml').text

doc

URLError: ignored

<h3>Membaca data dari modul</h3
<p>Contoh dataset dokumen yang cukup tenar: &quot;20 NewsGroup&quot;</p>

<img alt="" src="figures/6_20News.jpg" style="height: 300px ; width: 533px" />
<p><a href="http://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_20newsgroups.html#sklearn.datasets.fetch_20newsgroups" target="_blank">http://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_20newsgroups.html#sklearn.datasets.fetch_20newsgroups</a></p>

<p><strong>Categories </strong>=&nbsp;</p>
<pre>
[&#39;alt.atheism&#39;, &#39;comp.graphics&#39;, &#39;comp.os.ms-windows.misc&#39;, &#39;comp.sys.ibm.pc.hardware&#39;, &#39;comp.sys.mac.hardware&#39;,
 &#39;comp.windows.x&#39;, &#39;misc.forsale&#39;, &#39;rec.autos&#39;, &#39;rec.motorcycles&#39;, &#39;rec.sport.baseball&#39;, &#39;rec.sport.hockey&#39;,
 &#39;sci.crypt&#39;, &#39;sci.electronics&#39;, &#39;sci.med&#39;, &#39;sci.space&#39;, &#39;soc.religion.christian&#39;, &#39;talk.politics.guns&#39;,
 &#39;talk.politics.mideast&#39;, &#39;talk.politics.misc&#39;, &#39;talk.religion.misc&#39;]</pre>


In [18]:
# Membaca teks dari modul
# note: butuh koneksi internet

from sklearn.datasets import fetch_20newsgroups

categories = ['sci.med', 'talk.politics.misc',  'rec.autos']
data = fetch_20newsgroups(subset='train', categories=categories,remove=('headers', 'footers', 'quotes'))

data.data[0]

'I want to get a car alarm and I am thinking about getting an Ungo Box.\n    Does anyone out there have any knowledge or experience with any of\n    these alarms?  How about price ranges for the different models?\n    Are these good car alarms?  Please email me any responces.\n\n                cak3@ns3.lehigh.edu'

In [21]:
# Agar tidak perlu mendownload kembali data, ada baiknya disimpan 
# jika dibutuhkan tinggal membacanya dari drive
# data dapat disimpan ke dalam bentuk pickle
import pickle

dst_name = "20newsgroups.pickle"

# wb = write binary
# w = write
# rb = read binary
# r = read
# with open(dst_path, 'wb') as fout:
#     pickle.dump(data, fout)

In [26]:
!wget https://github.com/coll-j/STKI-assignments/blob/main/data/20newsgroups.pickle?raw=true -O 20newsgroups.pickle

--2021-09-19 13:01:01--  https://github.com/coll-j/STKI-assignments/blob/main/data/20newsgroups.pickle?raw=true
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://github.com/coll-j/STKI-assignments/raw/main/data/20newsgroups.pickle [following]
--2021-09-19 13:01:01--  https://github.com/coll-j/STKI-assignments/raw/main/data/20newsgroups.pickle
Reusing existing connection to github.com:443.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/coll-j/STKI-assignments/main/data/20newsgroups.pickle [following]
--2021-09-19 13:01:01--  https://raw.githubusercontent.com/coll-j/STKI-assignments/main/data/20newsgroups.pickle
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.108.133, 185.199.111.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199

In [27]:
# Membaca data dari pickle

src_name = dst_name

with open(src_name, 'rb') as fin:
    data_pckl = pickle.load(fin)

data_pckl.data[0]

'I want to get a car alarm and I am thinking about getting an Ungo Box.\n    Does anyone out there have any knowledge or experience with any of\n    these alarms?  How about price ranges for the different models?\n    Are these good car alarms?  Please email me any responces.\n\n                cak3@ns3.lehigh.edu'

In [28]:
len(data_pckl.data)

1653

### Representasi vektor

<ul>
    <li>Data teks tidak dapat secara langsung dianalisis dengan model statistik/ data mining</li>
    <li>Data teks terlebih dahulu harus diolah melalui tahapan pre-processing dan kemudian direpresentasikan ke dalam bentuk yang lebih sederhana (vektor) agar dapat dengan mudah untuk diolah</li>
    <li>Akan tetapi perubahan data ke dalam bentuk yang lebih sederhana dapat berakibat pada hilangnya beberapa informasi dari data tersebut. Contohnya pada metode <strong> bag-of-words </strong> informasi urutan antar kata hilang </li>
</ul>

<h3> Vector Space Model (VSM) </h3>
<p> VSM merepresentasikan sebuah kata ke dalam bentuk vektor dalam suatu dimensi spasial. </p>

<p><img alt="" src="figures/vsm.png" style="width: 300px; height: 213px;" /></p>


<h4> Contoh representasi vektor antara term dengan dokumen: </h4>
<p><img alt="" src="figures/3_Bentuk umum representasi dokumen.JPG" style="height: 294px ; width: 620px" /></p>

<p><img alt="" src="figures/vsm_matrix.png" style="width: 500px; height: 283px;" /></p>

In [35]:
# Contoh pembentukan representasi vektor dengan perhitungan frekuensi (VSM-TF)
# dapat menggunakan library CountVectorizer pada sklearn
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
'This is is the first document.',
'This document is the second document.',
'And this is the third one.',
'Is this the first document?',
]
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())
print(X.toarray())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 2 0 0 1 0 1]
 [0 2 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


<h4> TF.IDF-Term Weighting </h4>
<ul>
    <li> Pada representasi vektor sebelumnya nilai antar term dengan dokumen hanya berupa frekuensi kemunculan saja </li>
    <li> Nilai antar term dengan dokumen dapat digantikan dengan bobot TF.IDF </li>
    <li> TF (Term Frequency) menghitung frekuensi dari suatu kata pada dokumen; sementara IDF (Inverse Document Frequency) menghitung nilai informatif dari suatu kata berdasarkan tingkat kemunculannya antar dokumen </li>

</ul>

<p><img alt="" src="figures/3_tfidf logic.jpg" style="height:359px; width:638px" /></p>

<h4> Rumus perhitungan TFIDF </h4>
<p><img alt="" src="figures/3_rumus tfidf.png" style="height:370px; width:367px" /></p>

<p><img alt="" src="figures/3_variant tfidf.png" style="height:300px; width:955px" /></p>

In [32]:
# Contoh pembentukan representasi vektor dengan TFIDF (VSM-TFIDF)
from sklearn.feature_extraction.text import TfidfVectorizer
corpus = [
'This is the first document.',
'This document is the second document.',
'And this is the third one.',
'Is this the first document?',
]
vectorizer_tfidf = TfidfVectorizer()
X_tfidf = vectorizer_tfidf.fit_transform(corpus)
print(vectorizer_tfidf.get_feature_names())
print(X_tfidf.toarray())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]
 [0.         0.6876236  0.         0.28108867 0.         0.53864762
  0.28108867 0.         0.28108867]
 [0.51184851 0.         0.         0.26710379 0.51184851 0.
  0.26710379 0.51184851 0.26710379]
 [0.         0.46979139 0.58028582 0.38408524 0.         0.
  0.38408524 0.         0.38408524]]


In [34]:
# Contoh pembentukan representasi vektor dengan binary 0 atau 1 (VSM-binary)
from sklearn.feature_extraction.text import CountVectorizer
corpus = [
'This is is the first document.',
'This document is the second document.',
'And this is the third one.',
'Is this the first document?',
]
vectorizer_binary = CountVectorizer(binary=True)
X_binary = vectorizer_binary.fit_transform(corpus)
print(vectorizer_binary.get_feature_names())
print(X_binary.toarray())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


<h3 id="Latihan:"><font color="blue">Latihan 1:</font></h3>

<p> Ubahlah data dari 20newsgroup dataset yang telah disimpan dalam bentuk pickle ke dalam representasi vektornya
<ul>
    <li> VSM binary </li>
    <li> VSM TF </li>
    <li> VSM TFIDF </li>
</ul>

<p> Apakah ukuran matriks yang terbentuk dari ketiga VSM tersebut sama? </p>
<p> Apakah baris kosong berpengaruh terhadap ukuran matriks yang terbentuk? </p>

In [36]:
!pip install gensim

In [37]:
# Kerjakan latihan 1 pada cell berikut ini
# In Progress
from sklearn.datasets import fetch_20newsgroups

categories = ['sci.med', 'talk.politics.misc',  'rec.autos']
data = fetch_20newsgroups(subset='train', categories=categories,remove=('headers', 'footers', 'quotes'))

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

# 1. VSM-Binary
print("1. VSM-Binary")
vectorizer_binary = CountVectorizer(binary=True)
X_binary = vectorizer_binary.fit_transform(data.data)
print(vectorizer_binary.get_feature_names())
X_binary_arr = X_binary.toarray()

print(X_binary_arr)
print(len(X_binary_arr))
print(len(X_binary_arr[0]))
print(len(X_binary_arr[100]))

print("-----------------------------------------------------------")
# 2. VSM-TF
print("2. VSM-TF")
vectorizer = CountVectorizer()
X_tf = vectorizer.fit_transform(data.data)
print(vectorizer.get_feature_names()[0:10])
X_tf_arr = X_tf.toarray()

print(X_tf_arr)
print(len(X_tf_arr))
print(len(X_tf_arr[0]))
print(len(X_tf_arr[100]))

print("-----------------------------------------------------------")
# 3. VSM-TFIDF
print("3. VSM-TFIDF")
vectorizer_tfidf = TfidfVectorizer()
X_tfidf = vectorizer_tfidf.fit_transform(data.data)
print(vectorizer_tfidf.get_feature_names()[0:100])
X_tfidf_arr = X_tfidf.toarray()

print(X_tfidf_arr)
print(len(X_tfidf_arr))
print(len(X_tfidf_arr[0]))
print(len(X_tfidf_arr[100]))

print("-----------------------------------------------------------")
# 4. Shape
print("4. Shape ketiga metode sama")


print("-----------------------------------------------------------")
# 5. blanks
print("5. Apakah baris kosong berpengaruh terhadap ukuran matriks yang terbentuk?")
data.data.append("")
data.data.append("")
data.data.append("")
X_binary = vectorizer_binary.fit_transform(data.data)
print(vectorizer_binary.get_feature_names())
X_binary_arr = X_binary.toarray()
print(len(X_binary_arr))
print("5. Berpengaruh")


1. VSM-Binary
['00', '000', '0000', '00014', '000k', '000mi', '000miles', '0010', '0033', '004021809', '00500', '008561', '00am', '00pm', '01', '011', '0119', '01720', '01830', '02', '02115', '02118', '02160', '024246', '025', '0278', '02908', '03', '0306', '0318', '0320', '0358', '0372', '03756', '04', '0400', '04046', '041', '0430', '0434', '045651', '0494', '05', '0502', '05401', '06', '0600', '06320', '06510', '0656', '07', '070', '0710', '0752', '08', '0804', '081', '084', '0845', '0878', '09', '0922', '0c', '0g', '0l', '0s', '10', '100', '1000', '100042', '10016', '1002', '10021', '1003', '10032', '1005', '100grams', '100k', '100mg', '100mph', '101', '1013', '1015', '10250', '1029', '103', '1031', '104', '1040', '10461', '1047', '1054', '105514', '106', '1064', '107', '1074', '10789', '108', '109', '1095', '10k', '10pm', '10th', '10w', '10w30', '10w40', '11', '110', '1100', '1101', '1102', '1111', '112', '1120', '1121', '1124', '112mph', '113', '114', '1142', '1143', '1147', '115

#### Custom TFIDF
* Menurut http://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html
* default formula tf-idf yang digunakan sk-learn adalah:
* $tfidf = tf * log(\frac{N}{df+1})$ ==> Smooth IDF
* namun kita merubahnya menjadi:
* $tfidf = tf * log(\frac{N}{df})$ ==> Non Smooth IDF
* $tfidf = (1+log(tf)) * log(\frac{N}{df+1})$ ==> sublinear_tf, Smooth IDF
* $tfidf = (1+log(tf)) * log(\frac{N}{df})$ ==> sublinear_tf, Non Smooth IDF

In [49]:
corpus = [
'This is the first document.',
'This document is the second document.',
'And this is the third one.',
'Is this the first document?',
]
tfidf_vectorizer = TfidfVectorizer(smooth_idf= False, sublinear_tf=True, lowercase=True)
tfidf = tfidf_vectorizer.fit_transform(corpus)
print(tfidf.shape) # Sama
print(tfidf_vectorizer.get_feature_names())
print(tfidf[0].data) # Hanya data ini yg berubah
print(tfidf[0].indices) # Letak kolomnya = tfidf

(4, 9)
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[0.46941728 0.61722732 0.3645444  0.3645444  0.3645444 ]
[1 2 6 3 8]


<h4 id="Zipf's-Law:--&quot;power-law&quot;-:">Zipf&#39;s Law: &quot;power law&quot; :</h4>

<img alt="" src="figures/zipf.png" style="width: 456px; height: 270px;" />
<ul>
	<li><a href="https://plus.maths.org/content/mystery-zipf" target="_blank">https://plus.maths.org/content/mystery-zipf</a></li>
	<li><a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4176592/" target="_blank">https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4176592/</a></li>
</ul>

In [41]:
# frequency filtering di VSM
# Menghilangkan term yg memiliki frequency kemunculan di banyak dokumen > threshold 
# dan term yang memiliki frequency kemunculan antar dokumen < threshold

tfidf_vectorizer = TfidfVectorizer()
tfidf_1 = tfidf_vectorizer.fit_transform(corpus)

tfidf_vectorizer_filter = TfidfVectorizer(max_df=0.75, min_df=1)
tfidf_2 = tfidf_vectorizer_filter.fit_transform(corpus)

print(tfidf_1.shape)
print(tfidf_vectorizer.get_feature_names())
print(tfidf_2.shape)
print(tfidf_vectorizer_filter.get_feature_names())

(4, 9)
['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
(4, 6)
['and', 'document', 'first', 'one', 'second', 'third']


<h3 id="Latihan:"><font color="blue">Latihan 2:</font></h3>

<ul>
    <li> Lakukan filtering pada VSM dari 20newsgroup dataset </li> 
    <li> Diskusikanlah, mengapa menghilangkan term yang memiliki frekuensi kemunculan tinggi antar dokumen?</li>
    <li> Mengapa menghilangkan term yang memiliki frekuensi kemunculan rendah antar dokumen? </li>
    <li> Mengapa perlu melakukan filtering berdasarkan frekuensi? </li>
</ul>

In [44]:
# Kerjakan latihan 2 pada cell berikut ini
newsgroup_vectorizer = TfidfVectorizer(max_df=0.75, min_df=0.01)
tfidf_newsgroup = newsgroup_vectorizer.fit_transform(data.data)

tfidf_newsgroup.shape

(1656, 1500)

### Ans
1. Kenapa menghilangkan term yang memiliki frekuensi tinggi?
> Karena kata yang sering muncul bisa jadi seperti stopword, tidak memiliki konteks atau makna yang terlalu berarti. Dan karena frekuensinya yang sangat banyak, kemungkinan bobotnya juga akan mendekati 0. Sehingga kurang diperlukan karena kurang berpengaruh banyak juga pada komputasi nantinya.

2. Kenapa menghilangkan term yang memiliki frekuensi rendah?
> Answer here

3. Mengapa perlu melakukan filtering berdasarkan frekuensi?
> Karena kita mau menghilangkan terms yang terlalu sering dan/atau jarang muncul. Pendekatan yang memungkinkan adalah mencari frekuensi kemunculannya cross documents. Frekuensi tersebut bisa digunakan untuk menentukan apakah term itu akan dihilangkan berdasarkan threshold yang ditentukan.

In [ ]:
# Model VSM dapat dipergunakan untuk N-gram
# Bermanfaat untuk menangkap term yang berupa frase
tfidf_vectorizer_ngram = TfidfVectorizer(ngram_range = (1,2))
tfidf_ngram = tfidf_vectorizer_ngram.fit_transform(corpus)

print("=====Without N-gram=====")
print(tfidf_vectorizer.vocabulary_)
print("=====With N-gram=====")
print(tfidf_vectorizer_ngram.vocabulary_)

<h3 id="Latihan:"><font color="blue">Latihan 3:</font></h3>

<ul>
    <li> Diskusikanlah, apakah n-gram efektif untuk menangkap term yang berupa frase? apakah hasil yang diperoleh dari n-gram SVM sudah memuaskan?
</ul>

In [ ]:
# Kerjakan latihan 3 pada cell berikut ini